# Generated by Django 6.1.1 on 2026-09-29 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('AUDIENCIA', 'Audiência'), ('PRAZO', 'Prazo'), ('REUNIAO', 'Reunião'), ('OUTRO', 'Outro')], default='PRAZO', max_length=20)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('inicio',),
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ('-atualizado_em',)},
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processo',
            name='area',
            field=models.CharField(choices=[('TRABALHISTA', 'Trabalhista'), ('CIVEL', 'Cível'), ('PREVIDENCIARIO', 'Previdenciário'), ('TRIBUTARIO', 'Tributário'), ('CRIMINAL', 'Criminal'), ('OUTRO', 'Outro')], default='TRABALHISTA', max_length=20),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_distribuicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='resultado',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('FAVORAVEL', 'Favorável'), ('DESFAVORAVEL', 'Desfavorável'), ('ACORDO', 'Acordo')], default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='processo',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_cnj',
            field=models.CharField(max_length=25),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['usuario', 'status'], name='api_process_usuario_0461e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('usuario', 'cpf_cnpj_hash'), name='cliente_documento_unico_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='processo',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('usuario', 'numero_cnj'), name='processo_cnj_unico_por_usuario'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='api.processo'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_agenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventoagenda',
            index=models.Index(fields=['usuario', 'inicio'], name='api_eventoa_usuario_679678_idx'),
        ),
    ]
